"""Réglages du chat : distances (px, à l'échelle ×1), durées (s), vitesses et poids."""

EDGE_MARGIN = 30
JUMP_UP = 650
JUMP_DOWN = 700
JUMP_REACH = 500
JUMP_APEX = 70
SCARED_FALL = 400
HEAD_HEIGHT = 60  # hauteur de la tête au-dessus des pieds, chat assis
ATTENTION = 220  # distance tête-curseur qui attire l'attention
PAW_RANGE = 90  # distance tête-curseur pour un coup de patte
WATCH_PATIENCE = 1.5  # secondes sans curseur avant de reprendre sa vie
WATCH_MAX = 30
HUNT_MIN, HUNT_MAX = 200, 800  # distance horizontale d'une proie au sol
HUNT_LEVEL = 120  # le curseur doit être posé à moins de ça au-dessus de la surface
HUNT_APPROACH = 150
HUNT_CHANCE = 0.5
HUNT_COOLDOWN = 20.0
BORED_AFTER = 8.0  # un curseur immobile depuis ce temps n'intéresse plus
PREY_FRESH = 20.0  # une proie immobile depuis plus longtemps n'est plus chassée
CURSOR_JITTER = 3
FEED_ROOM = (45, 185)  # place nécessaire à gauche / à droite du chat pour le placard (3 portes)
DRINK_ROOM = (80, 125)  # … pour la bouteille de lait
EAT_CYCLES = (3, 5)  # tours de la porte qu'il pousse de l'intérieur (1,25 s) pendant qu'il mange
LAP_CYCLES = (8, 14)  # coups de langue dans le lait renversé (0,5 s)
FISH_WATCH = (1, 2)  # tours du poisson dans son bocal (3,5 s), assis à le regarder
FISH_NOSE = (1, 2)  # … le nez collé au bocal (2,75 s)
PRINTS_ROOM = (65, 50)
FISHBOWL_ROOM = (35, 50)
TV_ROOM = (45, 45)
YARN_ROOM = (30, 200)  # place pour bondir sur la pelote pendue à sa ficelle
TV_TIME = (12, 25)
CLIMB_SPEED = 70.0  # px/s
CLIMB_LIFT = 24  # le chat quitte le sol en se dressant contre la vitre
CLIMB_TOP_DROP = 69  # pieds du chat accroché, sous le bord, au début de climb_top
CLIMB_MIN = 120  # une fenêtre moins haute que ça au-dessus du chat : on saute
BALL_AT_FEET = 38  # px entre les pieds du chat assis et la pelote que dessinent yarn_sniff / yarn_pat
BAT_FROM = 44  # … et celle de la 2e image de yarn_bat, d'où la vraie pelote repart
BAKED_BALL = frozenset({"yarn_sniff", "yarn_pat", "yarn_unroll", "yarn_follow", "yarn_bat_away",
                        "beach_sit", "mouse_near", "mouse_pounce", "mouse_play",
                        "mouse_upright"})  # balle (ou jouet) dessinée par les images du chat
BEACH_LAUNCH = (3, 66)  # ballon : il quitte la patte à la 4e image de beach_pat, à 66 px des pieds
MOUSE_SPEED = 60  # px/s : la souris mécanique avance de 6 px par image, comme dessinée
MOUSE_NEAR = 107  # px : où les images du chat (511) la dessinent quand elle arrive
MOUSE_FROM = 137  # … et d'où elle repart (514, 14e image)
MOUSE_WALK = (350, 450)  # px qu'elle parcourt pour venir jusqu'au chat
MOUSE_PLAY = (1, 3)  # tours de patte sur la souris (513 0-5 ; l'original en fait un, puis 6-14)
MOUSE_WAIT = 15.0  # s : patience du chat qui l'attend
BALL_LAUNCH = {"yarn_bat": (1, BAT_FROM), "beach_pat": BEACH_LAUNCH,
               "mouse_release": (13, MOUSE_FROM)}  # (image, px des pieds)
BEACH_ROUNDS = (2, 4)  # tapes avant de bondir dessus et de le crever
BEACH_SPEED = (120, 260)  # px/s : un ballon léger, tapoté, qui roule loin
BEACH_REST = (1.0, 3.0)  # s assis à côté, avant de le tapoter
BEACH_POUNCE_REACH = 112  # px : le bond final (planche 501) dessine le chat jusque-là, côté ballon
BAT_SPEED = (160, 460)  # px/s
AWAY_SPEED = (380, 560)  # dernier coup de patte, quand la place manque pour le final d'origine
BAT_HOP = (0, 380)  # px/s vers le haut
BALL_ROUNDS = (4, 7)  # tours de jeu ; le dernier finit par le final d'origine (elle se déroule et s'en va)
PAT_ROUNDS = (1, 3)
BALL_CATCH = 30  # px : la pelote est « aux pieds » (il se recale en s'asseyant)
POUNCE_RANGE = (160, 360)  # px : distance d'où il bondit sur la pelote (plus près, le bond fait du sur-place)
POUNCE_CHANCE = 0.6
BAT_ROOM = 400  # px : place qu'il veut devant la pelote pour la renvoyer sans faire le tour
LEAP_RUNUP = 180  # px : élan avant de sauter vers une pelote posée sur une autre surface
BALL_PATIENCE = 12.0  # s : attend qu'on lâche la pelote ou qu'elle retombe
REACH_TRIES = 12
FINALE_ROOM = 200  # place pour yarn_unroll … yarn_bat_away
DANGLE_BALL = (14, 28)  # pelote au bout de sa ficelle, dans la cellule de yarn_dangle
TOSS_HEIGHT = 260  # px : lancée d'un bord de l'écran, à cette hauteur au-dessus du chat
TOSS_SPEED = (350, 600)
TOSS_WATCH = 5.0
BOX_HOP_X = (120, 240)  # sortie de la boîte, vers le chat
BOX_HOP_Y = (420, 560)
BALL_OUT_WEIGHT = 20  # envie de jouer avec une pelote qui traîne
AWAY_TIME = (60, 300)  # s dehors, après une sortie par la chatière
EDGE_REACH = 20  # px entre les pieds et le bord qu'il regarde : ses pattes avant au ras du bord
EDGE_WEIGHT = 6
EDGE_JUMP_CHANCE = 0.5  # après avoir regardé en bas, il saute (sinon il recule)
EDGE_MIN_DROP = 40  # px : il ne saute que vers une surface au moins aussi bas
EDGE_LAND = (80, 220)  # px au-delà du bord où il retombe
OUTING_ROOM = (30, 110)
FROG_HOP = (0, 30, 60, 60, 60)  # px parcourus à chaque image du saut : ±30 px en l'air (images 1 et 2), comme la DLL
FROG_HOP_FPS = 10
FROG_APPROACH_PAUSE = (0.3, 0.9)  # s posée entre deux sauts, quand elle arrive
FROG_WALK = (450, 600)  # px qu'elle parcourt pour venir jusqu'au chat
FROG_NEAR = 220  # px : à cette distance, il se met à l'affût
FROG_ROUNDS = (2, 4)  # bonds du chat
FROG_FLEE = (2, 3)  # sauts pour lui échapper
FROG_ROOM = 150  # px : moins de place devant elle, elle file de l'autre côté, par-dessus le chat
FROG_WAIT = 25.0  # s : il la regarde partir
SCRATCH_ROOM = {"left": (145, 65), "right": (65, 145)}  # griffures sur la vitre (extension Mischief)
SCRATCH_CYCLES = (3, 5)  # l'original en fait 4, de 1,2 s
PLANT_ROOM = (70, 225)
BIN_ROOM = (60, 235)
TEAR_ROOM = (55, 150)  # déchirure dans l'écran (extension More Mischief)
BUTTERFLY_ROOM = (45, 200)
LEAVES_ROOM = (60, 240)
WALK_ON = 80  # px de marche après la scène, le temps que l'accessoire s'efface
CAN_ROOM = (55, 85)  # pâtée Felix (extension Feeding)
CARTON_ROOM = (55, 125)  # lait Felix
HOLD_PATIENCE = 60.0  # s : il attend qu'on serve, puis passe à autre chose
WAG_NEAR = 100  # px : le curseur (l'objet tenu) si près de sa tête, il remue la queue
TREAT_FALL = 200.0  # px/s : vitesse de départ d'une friandise lâchée du sachet
TREAT_REACH = (36, 35)  # px entre ses pieds et la friandise qu'il croque, tourné à droite / à gauche
TREAT_FOOD = 0.15  # une friandise, une petite part de repas
KITTEN_FOLLOW = 90  # px : Felix plus loin que ça, le chaton le suit (extension Kitten)
KITTEN_NEAR = 70  # px de Felix où il s'arrête
KITTEN_TROT = 200  # px : plus loin, il trotte
KITTEN_WAIT = 15.0  # s : Felix attend que le chaton vienne pour une scène à deux
KITTEN_CARRY = 215  # px : Felix porte le chaton sur cette distance, comme l'original
KITTEN_MILK_ROOM = (30, 125)
KITTEN_TAIL_ROOM = (101, 76)
KITTEN_RUB_ROOM = (104, 70)
KITTEN_FLAP_ROOM = (35, 140)
